import generateCSharpFields from './CSharpFieldGen.js';
import CSharpField from './CSharpField.js';

// Generate the C# code for the class with field info
export function generateCsharpCode(glyphs, importedCSharpFieldMappings, settings) {
    return generateCSharpClassCode({
        className: settings.className,
        fields: generateCSharpFields(glyphs, importedCSharpFieldMappings, settings)
    });
}

/**
 * @param {Object} o
 * @param {string} o.className 
 * @param {CSharpField[]} o.fields 
 */
function generateCSharpClassCode({ className, fields }) {
    if (!className)
        className = "IconFont";

    let s = '';
    s += '// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code';
    s += "\n// If you change the class to 'public' in order to use it outside its assembly, you should also change the fields from 'const' to 'static readonly'";
    s += `\nstatic class ${className}`;
    s += "\n{";
    fields.sort(f => f.name).forEach(f => s += generateCSharpCodeForField(f));
    s += "\n}";

    return s;

    function generateCSharpCodeForField(field) {
        return `\n\tpublic const string ${field.name} = "${field.value}";`;
    }
}

/*
function generateXAMLCode(fontName, fontFileName) {
    const s = `<OnPlatform x:Key="IconsFontFamily"\n            x:TypedArguments="x:String"\n            Android=\"${fontFileName}#${fontName}\"\n            iOS="${fontName}" />`;
    return htmlEncode(s);
}*/