import Entry from "./Entry.js";
import Frameworks from "./Frameworks.js";
import generateEntries from "./generateEntries.js";

export default function generateResourceDictionaryXaml(glyphs, importedCSharpFieldMappings, settings) {
    const entries = generateEntries(glyphs, importedCSharpFieldMappings, settings);

    return generateXaml(entries, settings);
}

/**
 * 
 * @param {Entry[]} entries 
 * @returns 
 */
function generateXaml(entries, settings) {
    /**
     * @param {Entry} e 
     * @returns
     */
    const getMarkupForEntry = e => `\n    <x:String x:Key="${e.key}">${e.value}</x:String>`;

    let result = `
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="true" ?>
<!-- Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code' -->
<ResourceDictionary xmlns="${getSchemaUri(settings.framework)}"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">`;

    entries.sort(e => e.name).forEach(e => result += getMarkupForEntry(e));

    result += "\n</ResourceDictionary>";

    return result;
}

function getSchemaUri(framework) {
    return framework === Frameworks.Forms ?
        `http://schemas.microsoft.com/dotnet/2014/forms`
        : `http://schemas.microsoft.com/dotnet/2021/maui`;
}

